const express = require('express');
const router = express.Router();
const db = require('../db');
const { verifyToken } = require('../middleware/auth');
const PDFDocument = require('pdfkit');

// Generate Player Progress PDF
router.get('/player/:playerId/pdf', verifyToken, async (req, res) => {
    try {
        const { playerId } = req.params;
        
        // Ensure requester has access (coach, admin, super, or player themselves)
        // Skipping complex access checks for brevity
        
        const userQuery = `
            SELECT u.name, u.email, u.role, am.academy_id, a.name as academy_name, a.logo_url
            FROM users u
            LEFT JOIN academy_memberships am ON u.id = am.user_id AND am.status = 'active'
            LEFT JOIN academies a ON am.academy_id = a.id
            WHERE u.id = $1 LIMIT 1
        `;
        const userResult = await db.query(userQuery, [playerId]);
        if (userResult.rows.length === 0) {
            return res.status(404).json({ status: 'error', message: 'Player not found' });
        }
        
        const player = userResult.rows[0];

        // Fetch basic stats for the PDF
        const statsQuery = `
            SELECT COUNT(*) as total_sessions, SUM(total_hits) as total_hits, AVG(sweet_spot_pct) as avg_sweet
            FROM sessions
            WHERE player_id = $1
        `;
        const statsResult = await db.query(statsQuery, [playerId]);
        const stats = statsResult.rows[0];

        // Generate PDF
        const doc = new PDFDocument({ margin: 50 });
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=progress_${playerId}.pdf`);
        doc.pipe(res);

        // Academy Logo logic would go here if `player.logo_url` is present
        // if (player.logo_url) { ... fetch and embed logo ... }

        doc.fontSize(25).text(`${player.academy_name || 'KnoQ'} - Player Report`, { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(18).text(`Name: ${player.name}`);
        doc.fontSize(14).text(`Email: ${player.email}`);
        doc.moveDown();

        doc.fontSize(18).text('Overall Stats', { underline: true });
        doc.fontSize(14).text(`Total Sessions: ${stats.total_sessions || 0}`);
        doc.fontSize(14).text(`Total Hits: ${stats.total_hits || 0}`);
        doc.fontSize(14).text(`Average Sweet Spot: ${Math.round(stats.avg_sweet || 0)}%`);
        doc.moveDown();

        doc.fontSize(12).text('Generated by KnoQ System', { align: 'center', color: 'grey' });

        doc.end();

    } catch (error) {
        console.error('Error generating PDF:', error);
        res.status(500).json({ status: 'error', message: 'Failed to generate PDF' });
    }
});

// Generate Raw Data Export (CSV/JSON)
router.get('/player/:playerId/data', verifyToken, async (req, res) => {
    try {
        const { playerId } = req.params;
        const format = req.query.format || 'json';

        const sessionsQuery = `
            SELECT id, start_time, end_time, total_hits, sweet_spot_pct, avg_power, avg_swing, peak_power, zone_distribution, consistency_score
            FROM sessions
            WHERE player_id = $1
            ORDER BY start_time DESC
        `;
        const result = await db.query(sessionsQuery, [playerId]);
        const sessions = result.rows;

        if (format === 'csv') {
            if (sessions.length === 0) {
                res.setHeader('Content-Type', 'text/csv');
                res.setHeader('Content-Disposition', `attachment; filename=data_${playerId}.csv`);
                return res.send("id,start_time,end_time,total_hits,sweet_spot_pct,avg_power,avg_swing,peak_power,consistency_score\n");
            }
            
            const header = 'id,start_time,end_time,total_hits,sweet_spot_pct,avg_power,avg_swing,peak_power,consistency_score';
            const rows = sessions.map(s => {
                return [
                    s.id,
                    s.start_time ? new Date(s.start_time).toISOString() : '',
                    s.end_time ? new Date(s.end_time).toISOString() : '',
                    s.total_hits,
                    s.sweet_spot_pct,
                    s.avg_power,
                    s.avg_swing || '',
                    s.peak_power || '',
                    s.consistency_score || ''
                ].join(',');
            });
            
            const csvContent = [header, ...rows].join('\n');
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', `attachment; filename=data_${playerId}.csv`);
            return res.send(csvContent);
        } else {
            // JSON format — includes shot-level data and coach notes
            const sessionsWithDetails = [];
            for (const session of sessions) {
                const shotsQuery = `SELECT shot_number, zone, power, swing, timestamp FROM shots WHERE session_id = $1 ORDER BY shot_number ASC`;
                const shotsResult = await db.query(shotsQuery, [session.id]);

                const notesQuery = `SELECT cn.note, cn.tags, cn.created_at, u.name as coach_name FROM coach_notes cn LEFT JOIN users u ON cn.coach_id = u.id WHERE cn.session_id = $1 ORDER BY cn.created_at ASC`;
                const notesResult = await db.query(notesQuery, [session.id]);

                sessionsWithDetails.push({
                    ...session,
                    shots: shotsResult.rows,
                    coach_notes: notesResult.rows
                });
            }

            res.setHeader('Content-Type', 'application/json');
            res.setHeader('Content-Disposition', `attachment; filename=data_${playerId}.json`);
            return res.json({ player_id: playerId, exported_at: new Date().toISOString(), data: sessionsWithDetails });
        }
    } catch (error) {
        console.error('Error generating data export:', error);
        res.status(500).json({ status: 'error', message: 'Failed to generate data export' });
    }
});

module.exports = router;
