// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7VcbqGV2ApvCqEimvMpoEDQnbTIKTqA',
    appId: '1:419313572643:web:7b3e1fdc1bd23f67a7ca96',
    messagingSenderId: '419313572643',
    projectId: 'coaches-eye-ai',
    authDomain: 'coaches-eye-ai.firebaseapp.com',
    storageBucket: 'coaches-eye-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWEr4uWDULN8rb10n_UvN_aLN4UieSog',
    appId: '1:419313572643:android:bb1a047e17f1f40ca7ca96',
    messagingSenderId: '419313572643',
    projectId: 'coaches-eye-ai',
    storageBucket: 'coaches-eye-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWEr4uWDULN8rb10n_UvN_aLN4UieSog',
    appId: '1:419313572643:ios:bb1a047e17f1f40ca7ca96',
    messagingSenderId: '419313572643',
    projectId: 'coaches-eye-ai',
    storageBucket: 'coaches-eye-ai.firebasestorage.app',
    iosBundleId: 'com.example.coachesEyeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWEr4uWDULN8rb10n_UvN_aLN4UieSog',
    appId: '1:419313572643:ios:bb1a047e17f1f40ca7ca96',
    messagingSenderId: '419313572643',
    projectId: 'coaches-eye-ai',
    storageBucket: 'coaches-eye-ai.firebasestorage.app',
    iosBundleId: 'com.example.coachesEyeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo7VcbqGV2ApvCqEimvMpoEDQnbTIKTqA',
    appId: '1:419313572643:web:7b3e1fdc1bd23f67a7ca96',
    messagingSenderId: '419313572643',
    projectId: 'coaches-eye-ai',
    authDomain: 'coaches-eye-ai.firebaseapp.com',
    storageBucket: 'coaches-eye-ai.firebasestorage.app',
  );
}
